# Generated by Django 3.1.1 on 2020-09-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190511_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='entry_4',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='entry_5',
        ),
    ]
